<?php
namespace App\Enums;

enum LogistOrderStatus: string
{
    case CREATED = 'CREATED';
    case ASSIGN_CARRIER = 'ASSIGN_CARRIER';
    case CARRIER_ASSIGNED = 'CARRIER_ASSIGNED';
    case IN_PROGRESS = 'IN_PROGRESS';
    case COMPLETED = 'COMPLETED';
    case WAITING_FOR_RECONCILIATION = 'WAITING_FOR_RECONCILIATION';
    case RECONCILIATION = 'RECONCILIATION';
    case DOCUMENTS_SUBMITTED = 'DOCUMENTS_SUBMITTED';
    case INCOMPLETE_SET = 'INCOMPLETE_SET';
    case DOCUMENTS_ACCEPTED = 'DOCUMENTS_ACCEPTED';
    case INVOICE_CREATED = 'INVOICE_CREATED';
    case PAID = 'PAID';
}
