name: Delivery Trans CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log into registry
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: cr.yandex
        username: json_key
        password: ${{ secrets.YCR_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cr.yandex/crpvffqsoktvsds0au65/dtrans-cp-application:latest
    - name: Push docker image to Registry
      run: docker push cr.yandex/crpvffqsoktvsds0au65/dtrans-cp-application:latest
